.TH "QLDV" "1" "" "" "qldv"
.SH NAME
\fBqldv\fR(1) - create a patched ld-linux\.so without version information warnings
.SH SYNOPSIS

\fBqldv\fR interpreter-to-patch [output=input-interpreter\.nodebug]


\fBqldv\fR -set executable-to-patch [output=-input-executable-interpreter\.nodebug]


\fBqldv\fR -find [executable=/bin/sh]


\fBqldv\fR -version

.SH DESCRIPTION

\fBqldv\fR creates a patched version of ld-linux\.so (the dynamic linker) that does not emit
warnings like these:

.nf
.RS
myprog: /usr/lib/libxyz.so: no version information available (required by myprog)
.RE

.fi

In its first form, \fBqldv\fR takes the first argument (an ld-linux\.so interpreter) and
creates a copy that does not emit version information warnings\. If a second argument is
given, it will be used as the location to place the new, patched linker\. If it is
omitted,the patched linker will be placed in the same directory as the input file,
with a \fB.nodebug\fR appended to the extension\. After running \fBqldv\fR, the user is still
responsible for having any executables use the new linker\.


In its second form, \fBqldv\fR takes an executable that is emitting version information
warnings\. It will both patch the dynamic linker the executable is using \fIand\fR patch the
executable to point to the new linker\. The second argument (the output path) is used
in the exact same way as before\.


In its third form, \fBqldv\fR will print the dynamic linker used by the given executable\.
If no argument is passed, \fB/bin/sh\fR will be used\. In this form, it is simply a thin
wrapper around \fBpatchelf --print-interpreter\fR\.


In its fourth form, \fBqldv\fR will print its version and license, and then exit\.

.SH EXAMPLES

Patch \fB/lib64/ld-linux.so.2\fR, saving the new version at \fB/lib64/ld-linux.so.2.nodebug\fR:

.nf
.RS
qldv /lib64/ld-linux.so.2
.RE

.fi

Patch \fB/lib64/ld-linux.so.2\fR, saving the new version at \fBpatched-linker.so\fR:

.nf
.RS
qldv /lib64/patched-linker.so
.RE

.fi

Assuming \fBmyprog\fR uses \fB/lib64/ld-linux.so.2\fR, patch \fB/lib64/ld-linux.so.2\fR, saving the
new version at \fB/lib64/ld-linux.so.2.nodebug\fR, and update \fBmyprog\fR to point to the new
version:

.nf
.RS
qldv -set myprog
.RE

.fi

Assuming \fBmyprog\fR uses \fB/lib64/ld-linux.so.2\fR, patch \fB/lib64/ld-linux.so.2\fR, saving the
new version at \fBpatched-linker.so\fR, and update \fBmyprog\fR to point to the new version:

.nf
.RS
qldv -set myprog patched-linker.so
.RE

.fi

Print the path to the dynamic linker used by \fB/bin/sh\fR:

.nf
.RS
qldv -find
.RE

.fi

Print the path to the dynamic linker used by \fBmyprog\fR:

.nf
.RS
qldv -find myprog
.RE

.fi
.SH AUTHOR

Ryan Gonzalez \\\fIrymg19@gmail.com\fR

.SH SEE ALSO

\fBld.so\fR(8)

